// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using rsFoodtrucks.Models;

namespace rsFoodtrucks.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250611173504_conregistro2")]
    partial class conregistro2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("rsFoodtrucks.Models.FT_Categorias", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnName("Nombre")
                        .HasColumnType("varchar(2000)")
                        .IsUnicode(false);

                    b.HasKey("IdCategoria")
                        .HasName("FT_ID_Categoria_PK");

                    b.ToTable("FT_Categorias");
                });

            modelBuilder.Entity("rsFoodtrucks.Models.FT_FoodtruckFT_Categoria", b =>
                {
                    b.Property<int>("Id_FT_FoodtruckFT_Categoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("IdCategoria")
                        .HasColumnType("integer");

                    b.Property<int>("IdFT")
                        .HasColumnType("integer");

                    b.HasKey("Id_FT_FoodtruckFT_Categoria");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdFT");

                    b.ToTable("FT_FoodtruckFT_Categoria");
                });

            modelBuilder.Entity("rsFoodtrucks.Models.FT_Foodtrucks", b =>
                {
                    b.Property<int>("IdFT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Activo")
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("true");

                    b.Property<string>("CartaMenu")
                        .HasColumnName("CartaMenu")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CelContacto")
                        .HasColumnName("CelContacto")
                        .HasColumnType("varchar(255)")
                        .IsUnicode(false);

                    b.Property<string>("Celiaco")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Celiaco")
                        .HasColumnType("char(1)")
                        .HasDefaultValue("N");

                    b.Property<string>("Consumo")
                        .HasColumnName("Consumo")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CuitCuil")
                        .HasColumnName("CuitCuil")
                        .HasColumnType("varchar(11)");

                    b.Property<byte[]>("DniDorso")
                        .HasColumnName("DniDorso")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("DniFrente")
                        .HasColumnName("DniFrente")
                        .HasColumnType("bytea");

                    b.Property<string>("DomicilioLegal")
                        .HasColumnName("DomicilioLegal")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EmailContacto")
                        .HasColumnName("Email")
                        .HasColumnType("varchar(255)")
                        .IsUnicode(false);

                    b.Property<string>("EmailTitular")
                        .HasColumnName("EmailTitular")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Emplazado")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Emplazado")
                        .HasColumnType("char(1)")
                        .HasDefaultValue("N");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnName("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<byte[]>("FtDerecha")
                        .HasColumnName("FtDerecha")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("FtFrente")
                        .HasColumnName("FtFrente")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("FtIzquierda")
                        .HasColumnName("FtIzquierda")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("FtTrasera")
                        .HasColumnName("FtTrasera")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("Habilitacion")
                        .HasColumnName("Habilitacion")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("Logo")
                        .HasColumnName("Logo")
                        .HasColumnType("bytea");

                    b.Property<string>("Menu")
                        .HasColumnName("Menu")
                        .HasColumnType("TEXT")
                        .HasMaxLength(10000);

                    b.Property<string>("NombreFantasia")
                        .IsRequired()
                        .HasColumnName("NombreFantasia")
                        .HasColumnType("varchar(2000)")
                        .IsUnicode(false);

                    b.Property<string>("NumeroRegistro")
                        .HasColumnName("NumeroRegistro")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SinTACC")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("SinTACC")
                        .HasColumnType("char(1)")
                        .HasDefaultValue("N");

                    b.Property<string>("SolicitudIngreso")
                        .HasColumnName("SolicitudIngreso")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Telefono")
                        .HasColumnName("Telefono")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Titular")
                        .IsRequired()
                        .HasColumnName("Titular")
                        .HasColumnType("varchar(2000)")
                        .IsUnicode(false);

                    b.Property<string>("Vegano")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Vegano")
                        .HasColumnType("char(1)")
                        .HasDefaultValue("N");

                    b.Property<string>("Vegetariano")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Vegetariano")
                        .HasColumnType("char(1)")
                        .HasDefaultValue("N");

                    b.HasKey("IdFT")
                        .HasName("FT_Id_Foodtruck_PK");

                    b.ToTable("FT_Foodtrucks");
                });

            modelBuilder.Entity("rsFoodtrucks.Models.FT_Usuarios", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Activo")
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("true");

                    b.Property<string>("Email")
                        .HasColumnName("Email")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnName("Usuario")
                        .HasColumnType("varchar(255)")
                        .IsUnicode(false);

                    b.HasKey("IdUsuario")
                        .HasName("FT_Usuaior_PK");

                    b.ToTable("FT_Usuarios");
                });

            modelBuilder.Entity("rsFoodtrucks.Models.FT_FoodtruckFT_Categoria", b =>
                {
                    b.HasOne("rsFoodtrucks.Models.FT_Categorias", "categorias")
                        .WithMany("FoodtrucksCategorias")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("rsFoodtrucks.Models.FT_Foodtrucks", "foodtrucks")
                        .WithMany("FoodtrucksCategorias")
                        .HasForeignKey("IdFT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
