CREATE TABLE public."FT_Preguntas" (
    "IdPregunta" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" varchar(255) NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "FT_Id_Pregunta_PK" PRIMARY KEY ("IdPregunta")
);

CREATE TABLE public."FT_Resenias" (
    "IdResenia" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "FoodtruckId" integer NOT NULL,
    "UsuarioId" integer NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "Comment" text NULL,
    CONSTRAINT "FT_Id_Resenia_PK" PRIMARY KEY ("IdResenia"),
    CONSTRAINT "FT_Resenias_FoodtruckId_fkey" FOREIGN KEY ("FoodtruckId") REFERENCES public."FT_Foodtrucks" ("IdFT") ON DELETE CASCADE,
    CONSTRAINT "FT_Resenias_UsuarioId_fkey" FOREIGN KEY ("UsuarioId") REFERENCES public."FT_Usuarios" ("IdUsuario") ON DELETE CASCADE
);

CREATE TABLE public."FT_Puntajes" (
    "ReseniaId" integer NOT NULL,
    "PreguntaId" integer NOT NULL,
    "Score" smallint NOT NULL,
    CONSTRAINT "FT_Id_Puntajes_PK" PRIMARY KEY ("ReseniaId", "PreguntaId"),
    CONSTRAINT "FT_Puntajes_PreguntaId_fkey" FOREIGN KEY ("PreguntaId") REFERENCES public."FT_Preguntas" ("IdPregunta") ON DELETE CASCADE,
    CONSTRAINT "FT_Puntajes_ReseniaId_fkey" FOREIGN KEY ("ReseniaId") REFERENCES public."FT_Resenias" ("IdResenia") ON DELETE CASCADE
);

CREATE INDEX "IX_FT_Puntajes_PreguntaId" ON public."FT_Puntajes" ("PreguntaId");

CREATE INDEX "IX_FT_Resenias_FoodtruckId" ON public."FT_Resenias" ("FoodtruckId");

CREATE INDEX "IX_FT_Resenias_UsuarioId" ON public."FT_Resenias" ("UsuarioId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260318153304_valoracoines', '3.1.32');

