<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <UserSecretsId>1cf675f6-1e77-4a31-b715-0a1bd184ffde</UserSecretsId>
    <ApplicationIcon />
    <OutputType>Exe</OutputType>
    <StartupObject />
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <WarningLevel>0</WarningLevel>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Data\**" />
    <Compile Remove="Models_proveedores\**" />
    <Compile Remove="Services\apisalud-main-Services\**" />
    <Compile Remove="Services\TsuService\**" />
    <Content Remove="Data\**" />
    <Content Remove="Models_proveedores\**" />
    <Content Remove="Services\apisalud-main-Services\**" />
    <Content Remove="Services\TsuService\**" />
    <EmbeddedResource Remove="Data\**" />
    <EmbeddedResource Remove="Models_proveedores\**" />
    <EmbeddedResource Remove="Services\apisalud-main-Services\**" />
    <EmbeddedResource Remove="Services\TsuService\**" />
    <None Remove="Data\**" />
    <None Remove="Models_proveedores\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Controllers\UserController.cs" />
    <Compile Remove="Controllers\WeatherForecastController.cs" />
    <Compile Remove="DataAccess\Interfaces\IRepository.cs" />
    <Compile Remove="DataAccess\Servicios\RepositoryJurisdiccion.cs" />
    <Compile Remove="Services\ExceptionService.cs" />
    <Compile Remove="Utility\LdapConnectionProvider.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Dockerfile" />
    <None Remove="Dockerfile.bak" />
  </ItemGroup>

  <ItemGroup>
  <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
  <PackageReference Include="EPPlus" Version="6.2.4" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="3.1.32" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="3.1.31" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.32" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="3.1.32" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.32" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.32">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="6.29.0" />
    <PackageReference Include="Novell.Directory.Ldap.NETStandard" Version="3.1.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="3.1.0" />
    <PackageReference Include="QRCoder" Version="1.4.3" />
    <PackageReference Include="System.Data.Odbc" Version="4.7.0" />
    <PackageReference Include="System.Text.Json" Version="6.0.7" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Exceptions\" />
  </ItemGroup>


</Project>


