CREATE TABLE public."FT_FoodtruckFT_Categoria" (
    "Id_FT_FoodtruckFT_Categoria" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "IdFT" integer NOT NULL,
    "IdCategoria" integer NOT NULL,
    CONSTRAINT "PK_FT_FoodtruckFT_Categoria" PRIMARY KEY ("Id_FT_FoodtruckFT_Categoria"),
    CONSTRAINT "FK_FT_FoodtruckFT_Categoria_FT_Categorias_IdCategoria" FOREIGN KEY ("IdCategoria") REFERENCES public."FT_Categorias" ("IdCategoria") ON DELETE CASCADE,
    CONSTRAINT "FK_FT_FoodtruckFT_Categoria_FT_Foodtrucks_IdFT" FOREIGN KEY ("IdFT") REFERENCES public."FT_Foodtrucks" ("IdFT") ON DELETE CASCADE
);

CREATE INDEX "IX_FT_FoodtruckFT_Categoria_IdCategoria" ON public."FT_FoodtruckFT_Categoria" ("IdCategoria");

CREATE INDEX "IX_FT_FoodtruckFT_Categoria_IdFT" ON public."FT_FoodtruckFT_Categoria" ("IdFT");

--select * from public."FT_FoodtruckFT_Categoria"