CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE SCHEMA IF NOT EXISTS dbo;

CREATE TABLE dbo."FT_Categorias" (
    "IdCategoria" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" varchar(2000) NOT NULL,
    CONSTRAINT "FT_ID_Categoria_PK" PRIMARY KEY ("IdCategoria")
);

CREATE TABLE dbo."FT_Usuarios" (
    "IdUsuario" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Usuario" varchar(255) NOT NULL,
    "Email" varchar(255) NULL,
    "Activo" boolean NULL DEFAULT (1),
    CONSTRAINT "FT_Usuaior_PK" PRIMARY KEY ("IdUsuario")
);

CREATE TABLE dbo."FT_Foodtrucks" (
    "IdFT" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "IdCategoria" integer NOT NULL,
    "NombreFantasia" varchar(2000) NOT NULL,
    "Logo" bytea NULL,
    "Titular" varchar(2000) NOT NULL,
    "Email" varchar(255) NULL,
    "Menu" TEXT NULL,
    "Vegano" char(1) NULL DEFAULT 'N',
    "Vegetariano" char(1) NULL DEFAULT 'N',
    "SinTACC" char(1) NULL DEFAULT 'N',
    "Emplazado" char(1) NULL DEFAULT 'N',
    "Celiaco" char(1) NULL DEFAULT 'N',
    "Activo" boolean NULL DEFAULT (1),
    CONSTRAINT "FT_Id_Foodtruck_PK" PRIMARY KEY ("IdFT"),
    CONSTRAINT "FK_FT_Foodtrucks_FT_Categorias_IdCategoria" FOREIGN KEY ("IdCategoria") REFERENCES dbo."FT_Categorias" ("IdCategoria") ON DELETE CASCADE
);

CREATE INDEX "IX_FT_Foodtrucks_IdCategoria" ON dbo."FT_Foodtrucks" ("IdCategoria");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230607111018_1', '3.1.32');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250325115355_sinRegistroFT', '3.1.32');

ALTER TABLE dbo."FT_Usuarios" SET SCHEMA public;

ALTER TABLE dbo."FT_Foodtrucks" SET SCHEMA public;

ALTER TABLE dbo."FT_Categorias" SET SCHEMA public;

ALTER TABLE public."FT_Usuarios" ALTER COLUMN "Activo" TYPE boolean;
ALTER TABLE public."FT_Usuarios" ALTER COLUMN "Activo" DROP NOT NULL;
ALTER TABLE public."FT_Usuarios" ALTER COLUMN "Activo" SET DEFAULT (true);

ALTER TABLE public."FT_Foodtrucks" ALTER COLUMN "Activo" TYPE boolean;
ALTER TABLE public."FT_Foodtrucks" ALTER COLUMN "Activo" DROP NOT NULL;
ALTER TABLE public."FT_Foodtrucks" ALTER COLUMN "Activo" SET DEFAULT (true);

ALTER TABLE public."FT_Foodtrucks" ADD "CartaMenu" varchar(100) NULL;

ALTER TABLE public."FT_Foodtrucks" ADD "CelContacto" varchar(255) NULL;

ALTER TABLE public."FT_Foodtrucks" ADD "Consumo" varchar(50) NULL;

ALTER TABLE public."FT_Foodtrucks" ADD "CuitCuil" varchar(11) NULL;

ALTER TABLE public."FT_Foodtrucks" ADD "DniDorso" bytea NULL;

ALTER TABLE public."FT_Foodtrucks" ADD "DniFrente" bytea NULL;

ALTER TABLE public."FT_Foodtrucks" ADD "DomicilioLegal" varchar(255) NULL;

ALTER TABLE public."FT_Foodtrucks" ADD "EmailTitular" varchar(255) NULL;

ALTER TABLE public."FT_Foodtrucks" ADD "FechaVencimiento" date NULL;

ALTER TABLE public."FT_Foodtrucks" ADD "FtDerecha" bytea NULL;

ALTER TABLE public."FT_Foodtrucks" ADD "FtFrente" bytea NULL;

ALTER TABLE public."FT_Foodtrucks" ADD "FtIzquierda" bytea NULL;

ALTER TABLE public."FT_Foodtrucks" ADD "FtTrasera" bytea NULL;

ALTER TABLE public."FT_Foodtrucks" ADD "NumeroRegistro" varchar(50) NULL;

ALTER TABLE public."FT_Foodtrucks" ADD "SolicitudIngreso" varchar(50) NULL;

ALTER TABLE public."FT_Foodtrucks" ADD "Telefono" varchar(100) NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250326120321_conRegistroFT', '3.1.32');

CREATE TABLE public."FT_FoodtruckFT_Categoria" (
    "Id_FT_FoodtruckFT_Categoria" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "IdFT" integer NOT NULL,
    "IdCategoria" integer NOT NULL,
    CONSTRAINT "PK_FT_FoodtruckFT_Categoria" PRIMARY KEY ("Id_FT_FoodtruckFT_Categoria"),
    CONSTRAINT "FK_FT_FoodtruckFT_Categoria_FT_Categorias_IdCategoria" FOREIGN KEY ("IdCategoria") REFERENCES public."FT_Categorias" ("IdCategoria") ON DELETE CASCADE,
    CONSTRAINT "FK_FT_FoodtruckFT_Categoria_FT_Foodtrucks_IdFT" FOREIGN KEY ("IdFT") REFERENCES public."FT_Foodtrucks" ("IdFT") ON DELETE CASCADE
);

CREATE INDEX "IX_FT_FoodtruckFT_Categoria_IdCategoria" ON public."FT_FoodtruckFT_Categoria" ("IdCategoria");

CREATE INDEX "IX_FT_FoodtruckFT_Categoria_IdFT" ON public."FT_FoodtruckFT_Categoria" ("IdFT");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250611173504_conregistro2', '3.1.32');

ALTER TABLE public."FT_Foodtrucks" DROP COLUMN "Activo";

ALTER TABLE public."FT_Foodtrucks" ALTER COLUMN "Vegetariano" TYPE text;
ALTER TABLE public."FT_Foodtrucks" ALTER COLUMN "Vegetariano" DROP NOT NULL;
ALTER TABLE public."FT_Foodtrucks" ALTER COLUMN "Vegetariano" DROP DEFAULT;

ALTER TABLE public."FT_Foodtrucks" ALTER COLUMN "Vegano" TYPE text;
ALTER TABLE public."FT_Foodtrucks" ALTER COLUMN "Vegano" DROP NOT NULL;
ALTER TABLE public."FT_Foodtrucks" ALTER COLUMN "Vegano" DROP DEFAULT;

ALTER TABLE public."FT_Foodtrucks" ALTER COLUMN "Celiaco" TYPE text;
ALTER TABLE public."FT_Foodtrucks" ALTER COLUMN "Celiaco" DROP NOT NULL;
ALTER TABLE public."FT_Foodtrucks" ALTER COLUMN "Celiaco" DROP DEFAULT;

ALTER TABLE public."FT_Foodtrucks" ALTER COLUMN "CartaMenu" TYPE bytea;
ALTER TABLE public."FT_Foodtrucks" ALTER COLUMN "CartaMenu" DROP NOT NULL;
ALTER TABLE public."FT_Foodtrucks" ALTER COLUMN "CartaMenu" DROP DEFAULT;

ALTER TABLE public."FT_Foodtrucks" ADD "Estado" char(1) NULL DEFAULT (true);

ALTER TABLE public."FT_Foodtrucks" ADD "Observaciones" text NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260312171626_conregistro_observaciones', '3.1.32');

