CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE SCHEMA IF NOT EXISTS dbo;

CREATE TABLE dbo."FT_Categorias" (
    "IdCategoria" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" varchar(2000) NOT NULL,
    CONSTRAINT "FT_ID_Categoria_PK" PRIMARY KEY ("IdCategoria")
);

CREATE TABLE dbo."FT_Usuarios" (
    "IdUsuario" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Usuario" varchar(255) NOT NULL,
    "Email" varchar(255) NULL,
    "Activo" boolean NULL DEFAULT (1),
    CONSTRAINT "FT_Usuaior_PK" PRIMARY KEY ("IdUsuario")
);

CREATE TABLE dbo."FT_Foodtrucks" (
    "IdFT" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "IdCategoria" integer NOT NULL,
    "NombreFantasia" varchar(2000) NOT NULL,
    "Logo" bytea NULL,
    "Titular" varchar(2000) NOT NULL,
    "Email" varchar(255) NULL,
    "Menu" TEXT NULL,
    "Vegano" char(1) NULL DEFAULT 'N',
    "Vegetariano" char(1) NULL DEFAULT 'N',
    "SinTACC" char(1) NULL DEFAULT 'N',
    "Emplazado" char(1) NULL DEFAULT 'N',
    "Celiaco" char(1) NULL DEFAULT 'N',
    "Activo" boolean NULL DEFAULT (1),
    CONSTRAINT "FT_Id_Foodtruck_PK" PRIMARY KEY ("IdFT"),
    CONSTRAINT "FK_FT_Foodtrucks_FT_Categorias_IdCategoria" FOREIGN KEY ("IdCategoria") REFERENCES dbo."FT_Categorias" ("IdCategoria") ON DELETE CASCADE
);

CREATE INDEX "IX_FT_Foodtrucks_IdCategoria" ON dbo."FT_Foodtrucks" ("IdCategoria");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230607111018_1', '3.1.32');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250325115355_sinRegistroFT', '3.1.32');

