CREATE TABLE public."FT_Categorias" (
    "IdCategoria" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" varchar(2000) NOT NULL,
    CONSTRAINT "FT_ID_Categoria_PK" PRIMARY KEY ("IdCategoria")
);

CREATE TABLE public."FT_Usuarios" (
    "IdUsuario" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Usuario" varchar(255) NOT NULL,
    "Email" varchar(255) NULL,
    "Activo" boolean NULL DEFAULT (true),
    CONSTRAINT "FT_Usuaior_PK" PRIMARY KEY ("IdUsuario")
);

CREATE TABLE public."FT_Foodtrucks" (
    "IdFT" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "IdCategoria" integer NOT NULL,
    "NombreFantasia" varchar(2000) NOT NULL,
    "Logo" bytea NULL,
    "Titular" varchar(2000) NOT NULL,
    "Email" varchar(255) NULL,
    "Menu" TEXT NULL,
    "Vegano" char(1) NULL DEFAULT 'N',
    "Vegetariano" char(1) NULL DEFAULT 'N',
    "SinTACC" char(1) NULL DEFAULT 'N',
    "Emplazado" char(1) NULL DEFAULT 'N',
    "Celiaco" char(1) NULL DEFAULT 'N',
    "Activo" boolean NULL DEFAULT (true),
    CONSTRAINT "FT_Id_Foodtruck_PK" PRIMARY KEY ("IdFT"),
    CONSTRAINT "FK_FT_Foodtrucks_FT_Categorias_IdCategoria" FOREIGN KEY ("IdCategoria") REFERENCES public."FT_Categorias" ("IdCategoria") ON DELETE CASCADE
);

CREATE INDEX "IX_FT_Foodtrucks_IdCategoria" ON public."FT_Foodtrucks" ("IdCategoria");


INSERT INTO public."FT_Usuarios"  ("Usuario", "Email", "Activo")
VALUES ('sebastianperez', 'sebastianperez@mardelplata.gob.ar', true);

INSERT INTO public."FT_Usuarios"  ("Usuario", "Email", "Activo")
VALUES ('jcgarcia', 'jcgarcia@mardelplata.gob.ar', true);

INSERT INTO public."FT_Usuarios"  ("Usuario", "Email", "Activo")
VALUES ('gdgutierrez', 'gdgutierrez@mardelplata.gob.ar', true);

INSERT INTO public."FT_Usuarios"  ("Usuario", "Email", "Activo")
VALUES ('tramirez', 'tramirez@mardelplata.gob.ar', true);

INSERT INTO public."FT_Categorias" ("Nombre")
VALUES ('Alimentos y bebidas');
