worker_processes 4;

events { worker_connections 1024; }

http {
    sendfile on;
    
    # 1. Ajuste de tamaño para las 9 imágenes del Foodtruck
    client_max_body_size 50M;

    proxy_buffer_size   128k;
    proxy_buffers   4 256k;
    proxy_busy_buffers_size   256k;
    large_client_header_buffers 4 16k;
    include mime.types;

    upstream app_servers {
        server 127.0.0.1:5000;
    }

    server {
        listen 80;

        # --- SECCIÓN FRONTEND (React) ---
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            try_files $uri $uri/ /index.html;
        }

        location ~* ^/(adm|mosaico|user|create|edit) {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            try_files $uri $uri/ /index.html;
        }

        # --- SECCIÓN API / BACKEND ---

        # Configuración específica para Auth (OIDC)
        location ~* ^/api/auth/ {
            proxy_pass         http://app_servers;
            proxy_redirect     off;
            
            # 2. CLAVE PARA EL ERROR DE CREDENCIALES: 
            # Informamos a .NET que el cliente original usó HTTPS
            proxy_set_header   X-Forwarded-Proto https;
            proxy_set_header   X-Forwarded-Port  443;
            
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Host $server_name;
        }

        # Rutas específicas de QR con restricciones de método
        location ~* ^/foodtruck/[0-9]+/generarqr$ {
            limit_except POST { deny all; }
            proxy_pass         http://app_servers;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   Authorization $http_authorization;
        }

        location ~* ^/foodtruck/[0-9]+/qr$ {
            limit_except GET { deny all; }
            proxy_pass         http://app_servers;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Resto de las rutas de la API (Categoría, Usuario, etc.)
        location ~* ^/(foodtruck|categoria|usuario|puntajes|resenias|preguntas|account/login) {
            proxy_pass         http://app_servers;
            proxy_redirect     off;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Host $server_name;
            
            # Recomendado: pasar el protocolo actual para evitar otros problemas de rutas
            proxy_set_header   X-Forwarded-Proto $scheme;
        }
    }
}